# Generated by Django 4.2.7 on 2024-01-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_userscurrentaddress_issuedesc_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userscurrentaddress",
            name="issue_status_id",
            field=models.CharField(blank=True, max_length=69, null=True),
        ),
    ]
