# Generated by Django 4.2.7 on 2024-01-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mech_name', models.CharField(blank=True, max_length=200, null=True)),
                ('booking_date', models.CharField(blank=True, max_length=200, null=True)),
                ('booking_time', models.CharField(blank=True, max_length=200, null=True)),
                ('issue_desc', models.CharField(blank=True, max_length=2000, null=True)),
                ('issue_resolved_status', models.CharField(blank=True, max_length=200, null=True)),
                ('mech_mobile', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'Bookings',
            },
        ),
    ]
