# Generated by Django 4.2.7 on 2024-02-02 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_userscurrentaddress_issuetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='mech_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='mech_username',
        ),
    ]
