# Generated by Django 4.2.7 on 2023-12-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_userscustomer"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookMechanic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issueid", models.CharField(max_length=10)),
                ("address", models.CharField(max_length=500)),
                ("zipcode", models.CharField(max_length=100)),
                ("vehicleType", models.CharField(max_length=100)),
                ("vehicleNo", models.CharField(max_length=10)),
                ("issuedesc", models.CharField(max_length=500)),
                ("phone", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "BookMechanic",
            },
        ),
    ]
