# Generated by Django 4.2.7 on 2023-12-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_bookmechanic"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmechanic",
            name="lat",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="bookmechanic",
            name="lng",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
