# Generated by Django 4.2.7 on 2024-01-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_userscurrentaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscurrentaddress',
            name='address',
            field=models.CharField(default=12, max_length=500),
            preserve_default=False,
        ),
    ]
