# Generated by Django 4.2.7 on 2024-01-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_userscurrentaddress_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscurrentaddress',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
