# Generated by Django 4.2.7 on 2024-01-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_userscurrentaddress_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmechanic',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='bookmechanic',
            name='issuedesc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='bookmechanic',
            name='issueid',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='bookmechanic',
            name='phone',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='bookmechanic',
            name='vehicleNo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bookmechanic',
            name='vehicleType',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bookmechanic',
            name='zipcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
