# Generated by Django 4.2.7 on 2024-01-29 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_bookings_cust_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="mech_name",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="mech_username",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
