# Generated by Django 4.2.7 on 2024-02-04 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_profile_mech_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscustomer',
            name='cust_email_verified',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
