# Generated by Django 4.2.7 on 2024-02-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_userscustomer_cust_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='issue_description',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], null=True),
        ),
    ]
