# Generated by Django 4.2.7 on 2024-01-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Mechanic", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking_status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issueid", models.CharField(blank=True, max_length=1000, null=True)),
                ("cust_name", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "cust_username",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("mech_name", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "mech_username",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("mech_assigned", models.CharField(max_length=50)),
                (
                    "issue_resolved_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("cust_lat", models.CharField(blank=True, max_length=200, null=True)),
                ("cust_lng", models.CharField(blank=True, max_length=200, null=True)),
                ("mech_lat", models.CharField(blank=True, max_length=200, null=True)),
                ("mech_lng", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "db_table": "Booking_status",
            },
        ),
    ]
