# Generated by Django 4.2.8 on 2023-12-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MechanicDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mech_Address", models.CharField(max_length=500)),
                ("mech_city", models.CharField(max_length=50)),
                ("mech_zipcode", models.CharField(max_length=30)),
                ("mech_shop", models.CharField(max_length=50)),
                ("username", models.CharField(max_length=100)),
                ("lat", models.CharField(blank=True, max_length=200, null=True)),
                ("lng", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "db_table": "MechanicDetails",
            },
        ),
        migrations.CreateModel(
            name="UsersMechanic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("username", models.CharField(max_length=100)),
                ("mobile", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "UsersMechanic",
            },
        ),
    ]
