# Generated by Django 4.2.7 on 2024-01-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Mechanic", "0002_booking_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking_status",
            name="mech_assigned",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
