# Generated by Django 4.2.7 on 2024-01-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mechanic', '0003_alter_booking_status_mech_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_status',
            name='duration_kilometers',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking_status',
            name='duration_seconds',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
