# Generated by Django 4.2.7 on 2024-02-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mechanic', '0006_profile_mechanic'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersmechanic',
            name='mech_email_verified',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
